### ISSUE TITLE
[Feature Request] Add model summary for Parameters, GFLOPs and FPS numbers

### ISSUE THREAD

**Issue by hellojialee** [tomas-gajarsky/facetorch#29]

**Comment by tomas-gajarsky** [comment]
I added the number of parameters of each model to the model tables in README v0.1.5. 

Computing the FLOPS needs to be done on the original model files, before exporting them to TorchScript, therefore I will have to see if I can still go easily back and get that info.

**Comment by hellojialee** [comment]
@tomas-gajarsky thumb up!
