### ISSUE TITLE
any model for 3d face reconstruction available?

### ISSUE THREAD

**Issue by flydragon2018** [tomas-gajarsky/facetorch#40]
need this .

**Comment by tomas-gajarsky** [comment]
[SynergyNet](https://github.com/choyingw/SynergyNet) can be used for 3D Face Reconstruction, however, facetorch currently utilizes it only for extracting 3D facial landmarks. The 3D face mesh utilizer is on the TODO list, but not being worked on at the moment.

I recommend having a look at the recent [HRN](https://younglbw.github.io/HRN-homepage/) project for detailed 3D Face Reconstruction.
