### ISSUE TITLE
Unable to add packages

### ISSUE THREAD

**Issue by tawichi** [tomas-gajarsky/facetorch#47]
Hi.

As written in the README, I followed these steps to add pandas

1. Add packages with corresponding versions to gpu.environment.yml file
2. Lock the environment: conda lock -p linux-64 -f gpu.environment.yml --lockfile gpu.conda-lock.yml
3. (Alternative Docker) Lock the environment: docker compose -f docker-compose.dev.yml run facetorch-lock-gpu
4. Install the locked environment: conda-lock install --name env gpu.conda-lock.yml

However, if I create a container after this procedure with "docker compose -f docker-compose.dev.yml run facetorch-dev-gpu", pandas is not added there. How can I add it?

**Comment by tomas-gajarsky** [comment]
Hi, I would suggest a few things:

1. Seach for pandas in the lock file - if it is not there, then the locking of env needs fixing
2. Make sure to build the image from scratch `docker compose -f docker-compose.dev.yml run facetorch-dev-gpu --build`

**Comment by tawichi** [comment]
I forgot to build from scratch. Thanks.
