### ISSUE TITLE
Dev Containers in VScode

### ISSUE THREAD

**Issue by tawichi** [tomas-gajarsky/facetorch#49]
I cannot get into Dev Containers in VScode with facetorch-dev-gpu in docker-compose.dev.yml.
On the other hand, in facetorch-dev-example, I could use VSCode dev containers. How can I use Dev Containers in facetorch-dev-gpu?

**Comment by tomas-gajarsky** [comment]
The Dev Containers extension in VSCode works the same with CPU and GPU containers for me. Could you specify what exactly went wrong with the GPU container for you?
