### ISSUE TITLE
What code should I use if I just want to use the FAU?

### ISSUE THREAD

**Issue by s0yabean** [tomas-gajarsky/facetorch#51]
Hello thanks for creating this awesome library :)

When I run the FaceAnalyzer object I notice it runs through all the modules - FAU, FER, Deepfake prediction and embeddings.

I was just looking for an FAU prediction - even when I tried removing the config for FER, Deepfake and the rest, but the code was unable to run, hence I'm not sure if I'm using the correct class. 

Which class/ config should I be using, and are there any dependencies for using FAU that I have to include, like steps to crop the image?

**Comment by tomas-gajarsky** [comment]
Hi, thanks for trying it out :)

All the models are enabled by default in the example script. If you are using that one, then you need to remove all the utilizers and the predictors except the AU predictor from the main `config.yaml` file in the `conf` folder.

I suspect that your code was failing because you didn't remove the utilizers, which depended on one of the removed predictors.

**Comment by s0yabean** [comment]
I see, I followed your advice as well as seen this:

https://github.com/tomas-gajarsky/facetorch/issues/48

and now I've removed most of the modules, cutting short the speed by at least 50%!

These are the current ones I'm using, I'm assuming they are necessary.

When I tried to remove "draw_boxes" under "utilizer", there was a loading error due to a missing key, so I ended up including "draw_boxes" even though I'm not using it.

{"asctime": "2023-08-07 09:51:57,078", "levelname": "INFO", "message": "Initializing FaceAnalyzer"}
{"asctime": "2023-08-07 09:51:57,080", "levelname": "INFO", "message": "Initializing BaseReader"}
{"asctime": "2023-08-07 09:51:57,099", "levelname": "INFO", "message": "Initializing FaceDetector"}
{"asctime": "2023-08-07 09:51:57,429", "levelname": "INFO", "message": "Initializing FaceUnifier"}
{"asctime": "2023-08-07 09:51:57,445", "levelname": "INFO", "message": "Initializing FacePredictor objects"}
{"asctime": "2023-08-07 09:51:57,446", "levelname": "INFO", "message": "Initializing FacePredictor au"}
{"asctime": "2023-08-07 09:51:58,392", "levelname": "INFO", "message": "Initializing BaseUtilizer objects"}
{"asctime": "2023-08-07 09:51:58,393", "levelname": "INFO", "message": "Initializing BaseUtilizer draw_boxes"}

Thanks for your help :)
