### ISSUE TITLE
 add the action unit intensity  estimation task  in this project

### ISSUE THREAD

**Issue by weiwuxian1998** [tomas-gajarsky/facetorch#55]
Hi, thanks for this outstanding project with various facial related tasks, but if you have the plan to add the action unit intensity estimation task in this project.

**Comment by tomas-gajarsky** [comment]
Thanks for your interest in facetorch! Currently, we offer facial action unit detection, but not action unit intensity estimation. We're open to suggestions, so if you have relevant projects in mind for this feature, feel free to share them for consideration.

**Comment by weiwuxian1998** [comment]
Thanks for your reply, I find the [https://github.com/ihp-lab/LibreFace](url) contains this task, and the authors also released the pretrained files which can be applied directly, I hope it can help.  And I also attempt to re-train the model on DISFA dataset using other backbone, once I get better preformance, I would inform you, Thanks.

**Comment by tomas-gajarsky** [comment]
Unfortunately, the project that you pointed me to was released under a restrictive license, therefore I can't integrate it.
Let me know if you find or create an open model though.
