### ISSUE TITLE
Still the original size after feeding into the reader

### ISSUE THREAD

**Issue by sun913** [tomas-gajarsky/facetorch#57]
Hi!

Thanks for your amazing work first! I only need to use au and pose predictor in the model. When the image runs on the Colab demo, it will return the image with size [3,1080,1080]. However, when I only ran on my Ubuntu system, it gave me [3,288,288], which is the original size of the image. I understood that the resizing of the image is important in the later step of detecting the face of the image. I can get the face in the Colab demo but can not detect the face from my end. Can you please help me with this? Thank you!

![screenshot](https://github.com/tomas-gajarsky/facetorch/assets/132712612/cb81a377-3694-465c-a975-e32c99347665)

**Comment by tomas-gajarsky** [comment]
You might want to change the fix_img_size parameter to True when running the reader. Let me know if that helps.

**Comment by sun913** [comment]
> You might want to change the fix_img_size parameter to True when running the reader. Let me know if that helps.

Yes, that helps! Thank you.

**Comment by tomas-gajarsky** [comment]
I am glad it worked. In case you want to change the image size from the default 1080 pixels, you can do so by adjusting the reader configuration.
