### ISSUE TITLE
Feature Request: Add a valnece-arousal model

### ISSUE THREAD

**Issue by tawichi** [tomas-gajarsky/facetorch#58]
Hi.
Thank you for maintaining this useful repository.
I found a [valence-arousal model](https://github.com/kdhht2334/ELIM_FER) (NeurIPS 2022) under an MIT license.
They uploaded some pre-trained weights. 
Could you add this to Facetorch?

**Comment by tomas-gajarsky** [comment]
This valence arousal model was just added in facetorch version 0.4.0

**Comment by tomas-gajarsky** [comment]
Thanks for your sponsorship contribution!

I have made some further adjustments. The default offset for the valence and arousal values is 0, but one can change it in the configuration of the postprocessor.
