### ISSUE TITLE
Running on specified GPU

### ISSUE THREAD

**Issue by Ravi2712** [tomas-gajarsky/facetorch#68]
Hi, How to run the analyzer on a second GPU or specified GPU node? For example, pytorch like framework allow us to run on `cuda:1`. I did not find a way to run this on specified node.

**Comment by tomas-gajarsky** [comment]
Facetorch indeed allows for the specification of GPU devices, similar to how you would do it in PyTorch. This can be done directly within the configuration files. Here are the steps you can follow to set a specific GPU device for running the analyzer:

- **Specify the Analyzer Device**: In your [configuration file, you can explicitly set the GPU device for the analyzer](https://github.com/tomas-gajarsky/facetorch/blob/main/conf/merged/gpu.merged.config.yaml#L2) (or [here](https://github.com/tomas-gajarsky/facetorch/blob/main/conf/analyzer/default.yaml#L1) in case you are not using the merged config file). This is done by setting the device in the same format used by PyTorch, for example, `cuda:1` for using the second GPU. This setting ensures that all predictors run on the specified GPU.

- **Individual Predictor Device Configuration**: If you require more granular control over the device allocation, such as assigning different predictors to different GPUs, you can do so by modifying the device setting for each predictor. Replace the `${analyzer.device}` type placeholder in the configuration file with the specific device string, following the PyTorch format, e.g., `cuda:0`, `cuda:1`, etc.
